Rewrite bootstrap

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -4,17 +4,13 @@ set -e
 set -x
 
 GITHUB_USERNAME=${GITHUB_USERNAME:-rjernst}
-EXTRA_VARS="-e github_username=$GITHUB_USERNAME"
-
 DOTFILES=/tmp/dotfiles
-ANSIBLE_ROOT=$DOTFILES/bootstrap
-export ANSIBLE_CONFIG=$ANSIBLE_ROOT/ansible.cfg
 
 clone_dotfiles() {
   if [ -d "$DOTFILES" ]; then
     rm -rf $DOTFILES
   fi
-  echo "---> cloning ansible scripts"
+  echo "---> cloning bootstrap scripts"
   git clone https://github.com/$GITHUB_USERNAME/dotfiles.git $DOTFILES
 }
 
@@ -27,27 +23,23 @@ bootstrap_macos() {
     # homebrew on arm it installed to /opt/homebrew
     export PATH=/opt/homebrew/bin:$PATH
   fi
-  command -v git &> /dev/null || {
-    echo "---> installing git"
-    brew install git
-  }
-  command -v git &> /dev/null || {
-    echo "---> installing python3"
-    brew install python3
-  }
-  command -v ansible &> /dev/null || {
-    echo "---> installing ansible"
-    brew install ansible
+  platform_install() {
+    brew install $1
   }
 }
 
 bootstrap_arch() {
-  echo "---> installing git"
-  pacman -S --noconfirm --needed git
-  echo "---> installing python3"
-  pacman -S --noconfirm --needed python3
-  echo "---> installing ansible"
-  pacman -S --noconfirm --needed ansible
+  platform_install() {
+    pacman -S --noconfirm --needed $1
+  }
+}
+
+bootstrap_unknown() {
+  echo "unsupported platform, cannot install dependencies"
+  platform_install() {
+    echo "Missing $1, please install it"
+    exit 1
+  }
 }
 
 get_platform() {
@@ -62,6 +54,17 @@ get_platform() {
   fi
 }
 
+install_package() {
+  command -v $1 &> /dev/null || {
+    echo "---> installing $1"
+    platform_install $1
+  }
+}
+
+install_dependencies() {
+  install_package git
+}
+
 PLATFORM=$(get_platform)
 echo "---> detected platform: $PLATFORM"
 ARCH=$(uname -m)
@@ -69,6 +72,7 @@ echo "---> detected architecture: $ARCH"
 EXTRA_VARS="$EXTRA_VARS -e os=$PLATFORM"
 
 eval bootstrap_$PLATFORM
+install_dependencies
 
 clone_dotfiles
 
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -5,24 +5,32 @@ DOTFILES=$HOME/.dotfiles
 setup_link() {
   src=$DOTFILES/$1
   dst=$HOME/$2
+  echo "$src -> $dst"
+  if [ "$src" -ef "$dst" ]; then
+    return
+  fi
   if [ -f "$dst" ]; then
     ln_opts=-f
-    echo "$src exists, overwriting"
+    >&2 echo "WARNING: $src exists, overwriting"
   fi 
-  echo "$src -> $dst"
   ln $ln_opts -s $src $dst
 }
 
 link_role() {
   echo "Adding role $1"
-  setup_link "zsh/roles/$1.zsh"                 ".zsh/plugins/$1.zsh"
-  install_file=$DOTFILES/zsh/roles/$1.install
-  if [ -f $install_file ]; then
-    source $install_file
+  role_dir=$DOTFILES/roles/$1
+  if [ ! -f $role_dir ]; then
+    echo "ERROR: No role dir at $role_dir"
+    return
   fi
+  setup_file=$role_dir/setup
+  if [ -f $setup_file ]; then
+    source $setup_file
+  fi
+  setup_link "$role_dir/zsh_plugin"             ".zsh/plugins/$1.zsh"
 }
 
-[ ! -d $HOME/.gradle ] && mkdir $HOME/.gradle
+mkdir -p $HOME/.gradle
 setup_link "gradle/properties"                  ".gradle/gradle.properties"
 
 setup_link "zsh/zshrc"                          ".zshrc"
@@ -34,20 +42,19 @@ for ZSH_PLUGIN in $DOTFILES/zsh/plugins/*; do
   NAME=$(basename $ZSH_PLUGIN)
   setup_link "zsh/plugins/$NAME"                ".zsh/plugins/$NAME"
 done
-zsh_roles=$DOTFILES/zsh/hosts/$(hostname).roles
-if [ ! -f $zsh_roles ]; then
-  zsh_roles=$HOME/.zshroles
+roles=$DOTFILES/hosts/$(hostname)/roles
+if [ ! -f $roles ]; then
+  roles=$HOME/.zshroles
 fi
-if [ -f $zsh_roles ]; then
+if [ -f $roles ]; then
   while read role; do
     link_role $role
-  done <$zsh_roles
+  done <$roles
 fi
 
-setup_link "tmux/conf"                          ".tmux.conf"
 mkdir -p $HOME/.ssh
 setup_link "ssh/config"                         ".ssh/config"
-ssh_host_config=$DOTFILES/ssh/host_configs/$(hostname)
+ssh_host_config=$DOTFILES/hosts/$(hostname)/ssh_host_config
 if [ -f $ssh_host_config ]; then
   setup_link "$ssh_host_config"                 ".ssh/host_config"
 fi
@@ -58,18 +65,12 @@ for VIMFILE in $DOTFILES/vim/*; do
   setup_link "vim/$NAME"                        ".vim/$NAME"
 done
 
-[ ! -d $HOME/.git ] && mkdir $HOME/.git
+mkdir -p $HOME/.git
 setup_link "git/config"                         ".gitconfig"
 setup_link "git/ignore"                         ".git/ignore"
 
-mkdir -p $HOME/.gnupg
-for GPGFILE in $DOTFILES/gpg/*; do
-  NAME=$(basename $GPGFILE)
-  setup_link "gpg/$NAME"                        ".gnupg/$NAME"
-done
-
 if [[ $OSTYPE == darwin* ]]; then
-  brewfile=macos/brewfiles/$(hostname).Brewfile
+  brewfile=hosts/$(hostname)/brewfile
 
   if [ -f $DOTFILES/$brewfile ]; then
     setup_link "$brewfile"                      ".Brewfile"
@@ -86,19 +87,6 @@ if [[ $OSTYPE == darwin* ]]; then
     ln -s ~/Library/Mobile\ Documents/com\~apple\~CloudDocs ~/iCloud
   fi
 fi
-
-mkdir -p $HOME/bin
-for bin_script in $DOTFILES/bin/*; do
-  name=$(basename $bin_script)
-  setup_link "bin/$name"                        "bin/$name"
-done
-for tool in $DOTFILES/tools/*; do
-  tool_name=$(basename $tool)
-  for bin_script in $tool/bin/*; do
-    name=$(basename $bin_script)
-    setup_link "tools/$tool_name/bin/$name"     "bin/$name"
-  done
-done
 
 echo ""
 echo "Config files are setup."
