More cleanup of bootstrap
Consolidated bootstrap into single script. Also moved macos scripts into
scripts dir

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -4,15 +4,7 @@ set -e
 set -x
 
 GITHUB_USERNAME=${GITHUB_USERNAME:-rjernst}
-DOTFILES=/tmp/dotfiles
-
-clone_dotfiles() {
-  if [ -d "$DOTFILES" ]; then
-    rm -rf $DOTFILES
-  fi
-  echo "---> cloning bootstrap scripts"
-  git clone https://github.com/$GITHUB_USERNAME/dotfiles.git $DOTFILES
-}
+DOTFILES=$HOME/.dotfiles
 
 bootstrap_macos() {
   command -v brew &> /dev/null || {
@@ -65,6 +57,51 @@ install_dependencies() {
   install_package git
 }
 
+ensure_ssh_key_exists() {
+  keyfile=$ssh_dir/$1
+  if [ ! -f $keyfile ]; then
+    echo "---> creating $keyfile"
+    ssh-keygen -f $keyfile -t ed25519 
+  fi
+}
+
+check_ssh_keys() {
+  ssh_dir=~/.ssh
+  # ensure directory exists
+  if [ ! -d $ssh_dir ]; then
+    echo "---> creating $ssh_dir"
+    mkdir $ssh_dir
+  fi
+  # with the correct permissions
+  if [ "$(ls -ld $ssh_dir | cut -f 1 -d ' ')" != "drwx------" ]; then
+    echo "---> setting permissions on $ssh_dir"
+    chmod 700 $ssh_dir
+  fi
+  ensure_key_exists id_ed25519
+  ensure_key_exists github_ed25519
+}
+
+clone_dotfiles() {
+  if [ -d $DOTFILES ]; then
+    echo "---> $DOTFILES exists, skipping clone"
+    return
+  fi
+  dotfiles_url=https://github.com/rjernst/dotfiles.git
+  if [ "$USER"=="rjernst" ]; then
+    dotfiles_url=git@github.com:rjernst/dotfiles.git
+    echo "---> Checking authentication with github"
+    ssh -T git@github.com &> /dev/null
+    if [ $? -ne 1 ]; then
+      echo "---> SSH authentication failed with github. Add the following ssh key to github:\n"
+      cat ~/.ssh/id_ed25519.pub
+      echo ""
+      read -s -k "?Press any key when ready to continue"
+    fi
+  fi
+  echo "---> cloning $dotfiles_url"
+  git clone $dotfiles_url $DOTFILES
+}
+
 PLATFORM=$(get_platform)
 echo "---> detected platform: $PLATFORM"
 ARCH=$(uname -m)
@@ -73,9 +110,7 @@ EXTRA_VARS="$EXTRA_VARS -e os=$PLATFORM"
 
 eval bootstrap_$PLATFORM
 install_dependencies
-
+check_ssh_keys
 clone_dotfiles
 
-echo "---> running local bootstrap" 
-source $DOTFILES/bootstrap/local-bootstrap
-
+source $DOTFILES/setup
